"""
Auto-generated Migumi nodes for ASMBLR.

This file is automatically generated by asmblr.auto_loader.
Do not edit this file manually - regenerate it instead.
"""

from typing import List
from ..expr_node import GLNode
from ..base import InputSocket
from ..simple_registry import register_node_decorator


@register_node_decorator
class NamedGeometry(GLNode):
    """# migumi.symbolic.base.NamedGeometry"""
    # Associate the expression class at class level for external tools
    import migumi.symbolic.base as _expr_mod
    expr_class = _expr_mod.NamedGeometry
    
    # Embed category metadata in the class
    node_category = "mxg"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for NamedGeometry."""
        self.arg_keys = ['name']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'name': 'str'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

def register_all_nodes() -> List[str]:
    """Return list of all auto-registered Migumi nodes."""
    # All nodes are registered via the @register_node_decorator
    return [
        "NamedGeometry",
    ]
