"""
Auto-generated SySL nodes for ASMBLR.

This file is automatically generated by asmblr.auto_loader.
Do not edit this file manually - regenerate it instead.
"""

from typing import List
from ..expr_node import GLNode
from ..base import InputSocket
from ..simple_registry import register_node_decorator


@register_node_decorator
class BoundedSolid(GLNode):
    """# sysl.symbolic.base.BoundedSolid"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.base as _expr_mod
    expr_class = _expr_mod.BoundedSolid
    
    # Embed category metadata in the class
    node_category = "sysl_base"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for BoundedSolid."""
        self.arg_keys = ['expr', 'bounding', 'bound_threshold']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr': 'Expr', 'bounding': 'Expr', 'bound_threshold': 'float'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class GeomOnlySmoothUnion(GLNode):
    """# sysl.symbolic.base.GeomOnlySmoothUnion"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.base as _expr_mod
    expr_class = _expr_mod.GeomOnlySmoothUnion
    
    # Embed category metadata in the class
    node_category = "sysl_base"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for GeomOnlySmoothUnion."""
        self.arg_keys = ['expr_0', 'expr_1', 'k']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr_0': 'Expr', 'expr_1': 'Expr', 'k': 'float'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatSolidV1(GLNode):
    """# sysl.symbolic.base.MatSolidV1"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.base as _expr_mod
    expr_class = _expr_mod.MatSolidV1
    
    # Embed category metadata in the class
    node_category = "sysl_base"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatSolidV1."""
        self.arg_keys = ['solid', 'material']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'solid': 'Expr', 'material': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatSolidV2(GLNode):
    """# sysl.symbolic.base.MatSolidV2"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.base as _expr_mod
    expr_class = _expr_mod.MatSolidV2
    
    # Embed category metadata in the class
    node_category = "sysl_base"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatSolidV2."""
        self.arg_keys = ['solid', 'material']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'solid': 'Expr', 'material': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatSolidV3(GLNode):
    """# sysl.symbolic.base.MatSolidV3"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.base as _expr_mod
    expr_class = _expr_mod.MatSolidV3
    
    # Embed category metadata in the class
    node_category = "sysl_base"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatSolidV3."""
        self.arg_keys = ['solid', 'material']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'solid': 'Expr', 'material': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatSolidV4(GLNode):
    """# sysl.symbolic.base.MatSolidV4"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.base as _expr_mod
    expr_class = _expr_mod.MatSolidV4
    
    # Embed category metadata in the class
    node_category = "sysl_base"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatSolidV4."""
        self.arg_keys = ['solid', 'material']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'solid': 'Expr', 'material': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatMixV4(GLNode):
    """# sysl.symbolic.materials.MatMixV4"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MatMixV4
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatMixV4."""
        self.arg_keys = ['expr_a', 'expr_b', 't']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr_a': 'Expr', 'expr_b': 'Expr', 't': 'float'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatRefV3(GLNode):
    """# sysl.symbolic.materials.MatRefV3"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MatRefV3
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatRefV3."""
        self.arg_keys = ['name']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'name': 'str'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatRefV4(GLNode):
    """# sysl.symbolic.materials.MatRefV4"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MatRefV4
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatRefV4."""
        self.arg_keys = ['name']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'name': 'str'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MaterialV1(GLNode):
    """# sysl.symbolic.materials.MaterialV1"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MaterialV1
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MaterialV1."""
        self.arg_keys = ['smpl_index']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'smpl_index': 'int'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MaterialV1V4(GLNode):
    """# sysl.symbolic.materials.MaterialV1V4"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MaterialV1V4
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MaterialV1V4."""
        self.arg_keys = ['albedo', 'mr']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'albedo': 'Vector[3]', 'mr': 'Vector[2]'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MaterialV2(GLNode):
    """# sysl.symbolic.materials.MaterialV2"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MaterialV2
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MaterialV2."""
        self.arg_keys = ['rgb']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'rgb': 'Vector[3]'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MaterialV3(GLNode):
    """# sysl.symbolic.materials.MaterialV3"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MaterialV3
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MaterialV3."""
        self.arg_keys = ['albedo', 'emissive', 'roughness', 'clearcoat', 'metallic']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'albedo': 'Vector[3]', 'emissive': 'Vector[3]', 'roughness': 'float', 'clearcoat': 'float', 'metallic': 'float'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MaterialV4(GLNode):
    """# sysl.symbolic.materials.MaterialV4"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.MaterialV4
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MaterialV4."""
        self.arg_keys = ['albedo', 'emissive', 'mrc']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'albedo': 'Vector[3]', 'emissive': 'Vector[3]', 'mrc': 'Vector[3]'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class NonEmissiveMaterialV3(GLNode):
    """# sysl.symbolic.materials.NonEmissiveMaterialV3"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.NonEmissiveMaterialV3
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for NonEmissiveMaterialV3."""
        self.arg_keys = ['albedo', 'roughness', 'clearcoat', 'metallic']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'albedo': 'Vector[3]', 'roughness': 'float', 'clearcoat': 'float', 'metallic': 'float'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class RegisterMaterial(GLNode):
    """# sysl.symbolic.materials.RegisterMaterial"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.materials as _expr_mod
    expr_class = _expr_mod.RegisterMaterial
    
    # Embed category metadata in the class
    node_category = "sysl_materials"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for RegisterMaterial."""
        self.arg_keys = ['name', 'material']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'name': 'str', 'material': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class Avoid(GLNode):
    """# sysl.symbolic.mat_solid_combinators.Avoid"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.mat_solid_combinators as _expr_mod
    expr_class = _expr_mod.Avoid
    
    # Embed category metadata in the class
    node_category = "sysl_combinators"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for Avoid."""
        self.arg_keys = ['expr_0', 'expr_1']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr_0': 'Expr', 'expr_1': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatColorOnly(GLNode):
    """# sysl.symbolic.mat_solid_combinators.MatColorOnly"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.mat_solid_combinators as _expr_mod
    expr_class = _expr_mod.MatColorOnly
    
    # Embed category metadata in the class
    node_category = "sysl_combinators"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatColorOnly."""
        self.arg_keys = ['expr_0', 'expr_1']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr_0': 'Expr', 'expr_1': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class MatSmoothColorOnly(GLNode):
    """# sysl.symbolic.mat_solid_combinators.MatSmoothColorOnly"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.mat_solid_combinators as _expr_mod
    expr_class = _expr_mod.MatSmoothColorOnly
    
    # Embed category metadata in the class
    node_category = "sysl_combinators"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for MatSmoothColorOnly."""
        self.arg_keys = ['expr_0', 'expr_1', 'k']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr_0': 'Expr', 'expr_1': 'Expr', 'k': 'float'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

@register_node_decorator
class Repel(GLNode):
    """# sysl.symbolic.mat_solid_combinators.Repel"""
    # Associate the expression class at class level for external tools
    import sysl.symbolic.mat_solid_combinators as _expr_mod
    expr_class = _expr_mod.Repel
    
    # Embed category metadata in the class
    node_category = "sysl_combinators"
    
    def __init__(self, *args, **kwargs):
        # Keep super init simple; expr_class is already bound at class-level
        super().__init__(*args, **kwargs)
    
    def _create_input_sockets(self):
        """Create input sockets for Repel."""
        self.arg_keys = ['expr_0', 'expr_1']
        self.default_values = {}
        self.is_variadic = False
        self.arg_types = {'expr_0': 'Expr', 'expr_1': 'Expr'}
        return {key: InputSocket(key, parent=self, value=self.default_values.get(key, None)) 
                for key in self.arg_keys}

def register_all_nodes() -> List[str]:
    """Return list of all auto-registered SySL nodes."""
    # All nodes are registered via the @register_node_decorator
    return [
        "BoundedSolid",
        "GeomOnlySmoothUnion",
        "MatSolidV1",
        "MatSolidV2",
        "MatSolidV3",
        "MatSolidV4",
        "MatMixV4",
        "MatRefV3",
        "MatRefV4",
        "MaterialV1",
        "MaterialV1V4",
        "MaterialV2",
        "MaterialV3",
        "MaterialV4",
        "NonEmissiveMaterialV3",
        "RegisterMaterial",
        "Avoid",
        "MatColorOnly",
        "MatSmoothColorOnly",
        "Repel",
    ]
